### ISSUE TITLE
Fatal error: Class 'tmhOAuth' not found in [path]/OAuth.php on line 19

### ISSUE THREAD

**Issue by 5vxssbdahves** [spacenate/surveygizmo-api-php#8]
Trying to use this wrapper, but gets the error message in the subject line above. Have tried to debug a bit, but unfortunately not comfortable enough in PHP to really figure out what I'm doing wrong. Have you encountered anything similar?

**Comment by spacenate** [comment]
Hello @5vxssbdahves,
It seems the necessary dependencies are not able to be loaded by PHP, I would guess because they have not been installed or because Composer's `autoload.php` file is not being included.

I took a look at surveygizmo-api-php's readme, and realized that I did leave a few details to the imagination. I have clarified these details in 2e9dd4997acfb2efea79602a5e6033f5c10e90c6 and 6e6036bfce01d6c0f815c5d9e9818f343bf59163.

Have you tried `composer install`, and are you including the `vendor/autoload.php` file? If you're not sure what that means, take a look at the this expanded example: https://github.com/spacenate/surveygizmo-api-php-example

Good luck
